server:
  port: 20420

spring:
  application.name: cipher-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: angularpay
      username: service_account
      password: service_account_password
      authentication-database: angularpay

angularpay:
  numberOfKeysToGenerate: 200
  minimumKeyCount: 200
  queueCheckIntervalInSeconds: 60
  redis:
    host: localhost
    port: 6379
    timeout: 10000